data:
  recordings: uat/data
model:
  path: uat/models
  n_workers: 10
output_dir: uat/out
aggregation:
  period_hours: 48
  overlap_hours: 24
feeding_detector:
  type: oss
  path: begging-analyzer
  args:
    model_path: uat/bca-models/opensoundscape.model
    extension: WAV
