data:
  recordings: ...
#  labels: ...
model:
  path: ...
  n_workers: 4
output_dir: out
aggregation:
  period_hours: 48
  overlap_hours: 24
feeding_detector:
  type: fe
  path: ...
  args:
    model_path: ...
    extension: WAV
