name: "Train model"

on: [ workflow_dispatch ]

permissions:
  contents: read

env:
  DATA_PATH: ~/Snowfinch-acoustics/AI_training_recordings

jobs:
  train:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Checkout submodules using a PAT
        run: |
          git config --file .gitmodules --get-regexp url | while read url; do
            git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.SNOWFINCHWIRE_ALL_CHECKOUT }}:${{ secrets.SNOWFINCHWIRE_ALL_CHECKOUT }}@github.com\//")
          done
          git submodule sync
          git submodule update --init --recursive
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Display project tree
        run: |
          tree -a
      - name: Run training
        run: |
          python -m sfw_brood.train
      - name: Archive trained model
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: _out/trained_model
